CREATE TABLE IF NOT EXISTS HISTORY_STATUS (
    ID SERIAL NOT NULL PRIMARY KEY,
    REASON VARCHAR(250) NOT NULL,
    UPDATER VARCHAR(250) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBJECT_ID       BIGINT NOT NULL,
    OBJECT_TYPE     VARCHAR(50) NOT NULL
)